In [94]:
!pip install numpy

In [95]:
import numpy as np


In [96]:
# numpy array
a=np.array([1,2,3,4,5,6,7,8])
a
print(type(a))

<class 'numpy.ndarray'>


In [97]:
print(a)

[1 2 3 4 5 6 7 8]


In [98]:
a[0]

1

In [99]:
a[1:3]

array([2, 3])

In [100]:
a.shape

(8,)

In [101]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [102]:
print(b[0,3])
print(b[1,3])

4
9


In [103]:
b.shape

(2, 5)

In [104]:
#array slicing
b[0,1:4]

array([2, 3, 4])

In [105]:
b[1,2:4]

array([8, 9])

In [106]:
#data type
c=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype='int')
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [134]:
#newarr=a.astype('i')
#newarr=a.astype("float")## int to float
newarr=a.astype("int")
#newarr=a.astype("bool")
print(newarr)

[1 2 3 4 5]


In [108]:
#1D-2D reshape
arr=np.array([1,2,3,4,5,6,7,8,9])
x=arr.reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [109]:
#multi dimensional
y=b.reshape(-1)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
#iterating array
for i in arr:
 print(i)

1
2
3
4
5
6
7
8
9


In [137]:
#join array
a=np.array([10,20,30,40])
b=np.array([50,60,70,80,])
#c=np.concatenate((a,b),axis=0)
c=np.stack((a,b),axis=1)
print(c)


[[10 50]
 [20 60]
 [30 70]
 [40 80]]


In [140]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#c=np.concatenate((a,b),axis=1)
#c=np.vstack((a,b))
#c=np.dstack((a,b))
c=np.hstack((a,b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [141]:
a=np.array([50,10,30,20])
print(np.sort(a))

[10 20 30 50]


In [114]:
a=np.array([1,2,3,4,5])
print(np.zeros((4,4),dtype='int'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [115]:
print(np.zeros((5,3),dtype='float'))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [116]:
print(np.ones((4,2),dtype='float'))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [117]:
print(np.full((3,3),2))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [118]:
print(np.full((3,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [119]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [120]:
#mathematical manipulation
A=np.array([1,2,3,4])
B=np.array([2,4,6,8])
print(np.add(A,B))

[ 3  6  9 12]


In [121]:
print(np.subtract(A,B))

[-1 -2 -3 -4]


In [122]:
print(np.multiply(A,B))

[ 2  8 18 32]


In [123]:
print(np.divide(A,B))

[0.5 0.5 0.5 0.5]


In [124]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sum(arr1,axis=1))#row wise sum up
print(np.sum(arr1,axis=0))##column wise sum up
print(np.mean(arr1,axis=0))##row wise mean


[15 40]
[ 7  9 11 13 15]
[3.5 4.5 5.5 6.5 7.5]


In [125]:
ran=np.random.random((2,4))
ran

array([[0.2373356 , 0.55472931, 0.56443775, 0.33047439],
       [0.49735244, 0.68719602, 0.36978532, 0.57894887]])

In [126]:
#random integer values array within a specific range
ran2=np.random.randint(10,1000,(3,5))
print(ran2)

[[597 247 778 797 274]
 [934 461 706 276 377]
 [397 461 318 644 765]]


In [144]:
# array of evenly space values-->specifing the number of the values required
d = np.linspace(2,20,5)
print(d)

[ 2.   6.5 11.  15.5 20. ]


In [128]:
# covert a list to a numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [129]:
c = np.random.randint(10,90,(5,5))
print(c)

[[45 31 32 46 49]
 [77 24 17 38 26]
 [44 40 42 68 16]
 [22 16 32 60 33]
 [79 59 58 25 75]]


In [130]:
# array dimension
print(c.shape)

(5, 5)


In [131]:
print(c.ndim)

2


In [132]:
print(c.size)

25


In [133]:
print(c.dtype)

int64
